name: ai4beg
channels:  
  - defaults
  - conda-forge
dependencies:  
  - python=3.10  
  - openai  
  - python-dotenv
  - notebook
  - ipywidgets
  - tiktoken
  - matplotlib
  - numpy
  - pandas
  - tqdm
